hashtag: ""

queries:
  - "говновоз"

filters:
  min_duration: 90
  max_duration: 600
  min_views: 100
  date_after: ""
  title_blacklist_rx: ""
  #"(?i)(8d|bass\\s*boosted|nightcore)"
  exclude_shorts: true
  require_music: false
  require_ai_marker: false
  require_artist_ref: false
  tag_or_title: false
  title_any:
    - "говновоз"

output:
  shuffle: true
  limit: 5000
