all:
  children:
    vps_root:
      hosts:
        external-vps:
          ansible_host: 5.45.94.101
      vars:
        ansible_user: root
    vps_edge:
      hosts: { }
      vars:
        ansible_user: root
