all:
  children:
    vps_root:
      hosts:
        external-vps:
          ansible_host: 5.45.94.101
      vars:
        ansible_user: root
        radio_domain: govnovoz-fm.fun
    vps_edge:
      hosts:
        ru-edge-vps:
          ansible_host: 185.4.64.21
      vars:
        ansible_user: root
        radio_edge_domain: ru.govnovoz-fm.fun
        radio_edge_origin_host: govnovoz-fm.fun
        radio_edge_origin_url: https://govnovoz-fm.fun
