all:
  children:
    vps_root:
      hosts:
        vps1:
          ansible_host: 5.45.94.101
      vars:
        ansible_user: root

    vps_radio:
      hosts:
        vps1:
          ansible_host: 5.45.94.101
      vars:
        ansible_user: radio

    vps_vpn:
      hosts:
        vps1:
          ansible_host: 5.45.94.101
      vars:
        ansible_user: radio
